root6: add graphviz dependency
See: https://github.com/Homebrew/homebrew-science/issues/5745

If graphiz is not installed on the user's system, everything
is fine. If graphviz was installed by another formula or manually,
the root6 build system picks up graphviz, and builds some code
needing graphviz. As the dependency was not explicitely set,
this obvisouly fails with:

error: 'gvc.h' file not found
^
1 error generated.

As there is no way to disable the part of the build that
needs graphviz, this is now set as a required dependency.

This also fixes:
* Stable: The URL https://fossies.org/linux/misc/root_v6.08.06.source.tar.gz is not reachable (HTTP status code 404)
* C: 34: col 17: Only use parentheses for ternary expressions with complex conditions.
* C: 94: col 28: Only use parentheses for ternary expressions with complex conditions.
* C: 95: col 29: Only use parentheses for ternary expressions with complex conditions.

The root6 file delivered by fossies is from a newer version, but as this
version is not marked as stable on the root6 website, the mirror has been
dropped.

Closes #5788.

Signed-off-by: Michka Popoff <michkapopoff@gmail.com>